/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FakeApp {
    }
}
declare global {
    interface HTMLFakeAppElement extends Components.FakeApp, HTMLStencilElement {
    }
    var HTMLFakeAppElement: {
        prototype: HTMLFakeAppElement;
        new (): HTMLFakeAppElement;
    };
    interface HTMLElementTagNameMap {
        "fake-app": HTMLFakeAppElement;
    }
}
declare namespace LocalJSX {
    interface FakeApp {
    }
    interface IntrinsicElements {
        "fake-app": FakeApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fake-app": LocalJSX.FakeApp & JSXBase.HTMLAttributes<HTMLFakeAppElement>;
        }
    }
}
