/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnotherDependent {
    }
}
declare global {
    interface HTMLAnotherDependentElement extends Components.AnotherDependent, HTMLStencilElement {
    }
    var HTMLAnotherDependentElement: {
        prototype: HTMLAnotherDependentElement;
        new (): HTMLAnotherDependentElement;
    };
    interface HTMLElementTagNameMap {
        "another-dependent": HTMLAnotherDependentElement;
    }
}
declare namespace LocalJSX {
    interface AnotherDependent {
    }
    interface IntrinsicElements {
        "another-dependent": AnotherDependent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "another-dependent": LocalJSX.AnotherDependent & JSXBase.HTMLAttributes<HTMLAnotherDependentElement>;
        }
    }
}
