/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DependentComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDependentComponentElement extends Components.DependentComponent, HTMLStencilElement {
    }
    var HTMLDependentComponentElement: {
        prototype: HTMLDependentComponentElement;
        new (): HTMLDependentComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dependent-component": HTMLDependentComponentElement;
    }
}
declare namespace LocalJSX {
    interface DependentComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dependent-component": DependentComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dependent-component": LocalJSX.DependentComponent & JSXBase.HTMLAttributes<HTMLDependentComponentElement>;
        }
    }
}
