/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeepDependent {
    }
}
declare global {
    interface HTMLDeepDependentElement extends Components.DeepDependent, HTMLStencilElement {
    }
    var HTMLDeepDependentElement: {
        prototype: HTMLDeepDependentElement;
        new (): HTMLDeepDependentElement;
    };
    interface HTMLElementTagNameMap {
        "deep-dependent": HTMLDeepDependentElement;
    }
}
declare namespace LocalJSX {
    interface DeepDependent {
    }
    interface IntrinsicElements {
        "deep-dependent": DeepDependent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deep-dependent": LocalJSX.DeepDependent & JSXBase.HTMLAttributes<HTMLDeepDependentElement>;
        }
    }
}
